### ISSUE TITLE
CSS value color

### ISSUE THREAD

**Issue by fn-ix** [Cammisuli/vscode-custom-theme#15]
Hi! The color of alphabetical values in CSS isn't distinguished from the color of properties; not sure if this is by design, however most color themes I've come across tend to give them different colors for better separation.

![image](https://user-images.githubusercontent.com/16854594/166121619-4130592b-d77f-426f-8604-3318c01ca400.png)

**Comment by Cammisuli** [comment]
Hey, thanks for the suggestion! I'll take a look to see what color would suit it.
